### ISSUE TITLE
[v1.1.4] Make input elements controllable

### ISSUE THREAD

**Issue by mitrotasios** [tremorlabs/tremor-npm#257]
### Tasks

**Package**
- [x] Create useControllableState hook to return state depending if component is controlled or uncontrolled
- [ ] Implement controllable behaviour for:
  - [ ] Dropdown
  - [ ] Datepicker
  - [ ] SelectBox
  - [ ] MultiSelectBox
- [ ] Add `defaultValue` and `id` prop to `TextInput` component
- [ ] Change `handleSelect` prop to `onValueChange`
- [ ] Add warnings
  - [ ] `handleSelect` will be deprecated
  - [ ] Warning: A component is changing a controlled input to be uncontrolled. [...]
  - [ ] Warning: You provided a `value` prop to a form field without an `onChange` handler. [...]

**Docs**
- [ ] Relevant adjustments for new features
- [ ] Note which prop should be used for controlled/uncontrolled mode
- [ ] Potentially manual on state handler when state is controlled

### Notes
- Reset input value with `null` instead of `undefined`
